name: Check Modified Assets

on: [pull_request]

jobs:
    build-pr:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: npm install and build
              run: |
                  npm install
                  npm run build
                  npm run list-assets -s > assets.txt
            - name: Archive build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: assets-txt
                  path: assets.txt
    build-trunk:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  ref: trunk
            - name: Use Node.js 16.x
              uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - name: npm install and build
              run: |
                  npm install
                  npm run build
                  npm run list-assets -s > trunk-assets.txt
            - name: Upload Artifact
              uses: actions/upload-artifact@v2
              with:
                  name: trunk-assets-txt
                  path: trunk-assets.txt
    compare-assets:
        needs: [build-pr, build-trunk]
        runs-on: ubuntu-latest
        steps:
            - name: Download assets
              uses: actions/download-artifact@v2
              with:
                  name: trunk-assets-txt
            - name: Download assets (trunk)
              uses: actions/download-artifact@v2
              with:
                  name: assets-txt
            - uses: LouisBrunner/diff-action@v0.1.0
              with:
                  old: trunk-assets.txt
                  new: assets.txt
                  mode: deletion
                  tolerance: mixed
                  token: ${{ secrets.GITHUB_TOKEN }}
                  notify_issue: true
